# -*- coding: utf-8 -*-
"""Day 6 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ESXewFtD846ATRt2u2n6o0-YjQ3NDsx

Day 6 Assignment :
1.list1=[1,2,3,4,5,7,8]

list2=["a","b","c","d","e"]
convert to a dictionary in one line code using list comprehension(without using zip method)
"""

list2= ['a','b','c','d','e']
list1= [1,2,3,4,5,6,7,8]
result = {}
for key in list2:
    for values in list1:
        result[key] = values
        list1.remove(values)
        break
print(str(result))