# -*- coding: utf-8 -*-
"""Day 5 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-rwrZ2XS6Iqx5Hwv-Ch6X7pvnt6nO1dU

Day 5 Assignment:
1.sort list in increasing order but all zeroes should be at right hand side.
"""

list = [0,1,2,10,4,1,0,56,2,0,1,3,0,56,0,4]
list.sort()
k=list.count(0);
print(list[k:]+list[:k])

"""2.Merge two sorted lists &produce one sorted list:
list1 = [10,20,40,60,70,80]
list2 = [5,15,25,35,45,60]
"""

list1 = [10,20,40,60,70,80]
list2 = [5,15,25,35,45,60]
MergedList =list1+list2
ResSortedList=[]
for i in range(min(MergedList),max(MergedList)+1):
    if i in MergedList:
        ResSortedList.append(i)
print(ResSortedList)